default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: first_app_development

test:
  <<: *default
  database: first_app_test
  adapter: postgresql

production:
  adapter: postgresql
  <<: *default
  database: first_app_production
  username: first_app
  password: <%= ENV["FIRST_APP_DATABASE_PASSWORD"] %>